---
title: Template
format:
  dark2-revealjs: default
author: 
  - name: Jonathan Jayes
    email: jonathan.jayes@ekh.lu.se
    affiliation: Lund University
date: last-modified
bibliography: refs.bib
favicon: _extensions/j-jayes/dark2/favicon.ico
---

## Introduction

*TODO* Create an example file that demonstrates the formatting and features of your format.

## More Information

You can learn more about controlling the appearance of RevealJS output here: <https://quarto.org/docs/presentations/revealjs/>

# Dark BG Title {.has-dark-background} 

# Inverted {.inverted}

## Alerts

[Alert]{.text-emphasis}

## `Some header`

some text

`some mono text`

Megatypos

`Megatypos`


an example with code, even if I never use it 

```python

def some_func(x):
  return x

```

Some source ([2023](2023))

## Alerts & Cross-refs {#sec-crossref}

To emphasize specific words or text, you can:

- Use the default `.alert` class, e.g. [important note]{.alert}.
- Use the `.fg` class for custom colour, e.g. [important note]{.fg style="--col: #e64173"}.
- Use the `.bg` class for custom background, e.g. [important note]{.bg style="--col: #e64173"}.

To cross-reference, you have several options, for example:

- Beamer-like `.button` class provided by this theme, e.g. [[Appendix]{.button}](#sec-appendix)
- Quarto's native cross-ref syntax, e.g., "See @sec-appendix."

## Citations

Citations follow the standard
[Quarto format](https://quarto.org/docs/authoring/footnotes-and-citations.html#citations)
and be sourced from BibLaTex, BibTeX, or CLS files. For example:

 - [Topic 1:]{.alert} Spatial Frictions [@Hsieh_Moretti_2019]

## References

::: {#refs}
:::

## Appendix {#sec-appendix}

```{r}
#| label: tbl-attsum
#| tbl-cap: Summary of the base R `attitude` dataset

modelsummary::datasummary_skim(attitude)
```

[[Back to main]{.button}](#sec-crossref)